In [ ]:
#############################################
# NUMPY
#############################################

In [1]:
# Neden NumPy? (Why Numpy?)
# NumPy Array'i Oluşturmak (Creating Numpy Arrays)
# NumPy Array Özellikleri (Attibutes of Numpy Arrays)
# Yeniden Şekillendirme (Reshaping)
# Index Seçimi (Index Selection)
# Slicing
# Fancy Index
# Numpy'da Koşullu İşlemler (Conditions on Numpy)
# Matematiksel İşlemler (Mathematical Operations)



In [ ]:
#############################################
# Neden NumPy?
#############################################

In [2]:
import numpy as np

In [3]:
a=[1,2,3,4]
b=[2,3,4,5]

In [5]:
ab=[]

for i in range(0,len(a)):
  ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [6]:
a=np.array([1,2,3,4])
b=np.array([b])
a*b ##without writing a loop can be the same thing done!

array([[ 2,  6, 12, 20]])

In [8]:
#############################################
# NumPy Array'i Oluşturmak (Creating Numpy Arrays)
#############################################

np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [11]:
np.zeros(10,dtype=int)#an array with zeros:0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(10,dtype=int)#an array with ones:1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.random.randint(0, 10, size=10)#create 10 random nubmer

array([6, 1, 4, 4, 7, 0, 1, 9, 9, 0])

In [15]:
np.random.normal(10, 4, (3, 4))#create 3x4 matrix

array([[11.44060859,  9.70300026, 12.66217575,  2.13016006],
       [ 6.11557439,  8.2849254 ,  5.95404102, 16.05360175],
       [ 5.00790883, 13.41302847,  5.52630343, 17.93426254]])

In [ ]:
#############################################
# NumPy Array Özellikleri (Attibutes of Numpy Arrays)
#############################################

In [ ]:
# ndim: boyut sayısı 
# shape: boyut bilgisi
# size: toplam eleman sayısı
# dtype: array veri tipi

a = np.random.randint(10, size=5)
a.ndim
a.shape
a.size
a.dtype

In [18]:
a = np.random.randint(10, size=5)
a

array([8, 5, 7, 9, 7])

In [19]:
a.ndim#dimenson of a

1

In [20]:
a.shape#shape of it

(5,)

In [21]:
a.size

5

In [23]:
a.dtype

dtype('int64')

In [ ]:
#############################################
# Yeniden Şekillendirme (Reshaping)
#############################################

In [24]:
np.random.randint(1, 10, size=9)

array([1, 4, 1, 2, 4, 5, 1, 7, 4])

In [25]:
np.random.randint(1, 10, size=9).reshape(3, 3)

array([[8, 8, 7],
       [6, 1, 3],
       [9, 8, 1]])

In [27]:
ar = np.random.randint(1, 10, size=9)
ar #9x1 array

array([1, 6, 7, 4, 1, 9, 9, 6, 8])

In [28]:
ar.reshape(3,3) #after reshaping 3x3

array([[1, 6, 7],
       [4, 1, 9],
       [9, 6, 8]])

In [29]:
#############################################
# Index Seçimi (Index Selection)
#############################################

In [30]:
a = np.random.randint(10, size=10)
a

array([4, 7, 5, 2, 3, 8, 5, 8, 1, 2])

In [31]:
a[0]#first element of it (index:0)

4

In [33]:
a[0:5]#index number start with 0!

array([4, 7, 5, 2, 3])

In [34]:
a[0]=99
a

array([99,  7,  5,  2,  3,  8,  5,  8,  1,  2])

In [36]:
m = np.random.randint(10, size=(3, 5))
m

array([[7, 4, 6, 3, 8],
       [8, 4, 0, 7, 0],
       [3, 6, 8, 6, 2]])

In [37]:
m[0,0]#row,column

7

In [38]:
m[1,1]

4

In [39]:
m[2,3]

6

In [43]:
m[2, 3] = 999 # we can also give a new value to that index
m

array([[  7,   4,   6,   3,   8],
       [  8,   4,   0,   7,   0],
       [  3,   6,   8, 999,   2]])

In [50]:
m

array([[7, 4, 6, 3, 8],
       [8, 4, 0, 7, 0],
       [3, 6, 8, 2, 2]])

In [51]:
m[:,0]# all row of column '0' >>>7/8/3

array([7, 8, 3])

In [52]:
m[1,:]#row:1 all columns

array([8, 4, 0, 7, 0])

In [53]:
m[0:2, 0:3]#row:from 0 to 2, columns: 0 to 3 but columns 3 and row 2 is not included!

array([[7, 4, 6],
       [8, 4, 0]])

In [ ]:
#############################################
# Fancy Index
#############################################

In [55]:
v=np.arange(0,30,3)#0to 30(30not included!)increasing 3by 3
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [56]:
v[1]

3

In [57]:
v[4]

12

In [58]:
catch=[1,2,3]
v[catch]#v[x] if x is a list >>this names fancy index

array([3, 6, 9])

In [ ]:
#############################################
# Numpy'da Koşullu İşlemler (Conditions on Numpy)
#############################################

In [61]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [ ]:
#######################
# With classic loop>>Klasik döngü ile
#######################

In [63]:
ab=[]
for i in v:
  if i<3:
    ab.append(i)
ab

[1, 2]

In [64]:
#with numpy
v[v<3]#how easy is it :))

array([1, 2])

In [65]:
v[v>3]

array([4, 5])

In [66]:
v[v!=3]

array([1, 2, 4, 5])

In [67]:
v[v==3]

array([3])

In [68]:
v[v>=3]

array([3, 4, 5])

In [ ]:
#############################################
# Matematiksel İşlemler (Mathematical Operations)
#############################################

In [69]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [70]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [71]:
v*5/10  

array([0.5, 1. , 1.5, 2. , 2.5])

In [72]:
v**2

array([ 1,  4,  9, 16, 25])

In [73]:
v-3

array([-2, -1,  0,  1,  2])

In [74]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [75]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [76]:
np.mean(v)

3.0

In [77]:
np.sum(v)

15

In [78]:
np.min(v)

1

In [79]:
np.max(v)

5

In [80]:
np.var(v)

2.0

In [84]:
v=np.subtract(v,1)
v

array([-2, -1,  0,  1,  2])

In [ ]:
#######################
#Solving Equation with Two Unknowns with NumPy
# NumPy ile İki Bilinmeyenli Denklem Çözümü
#######################

In [93]:
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [94]:
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])

In [97]:
xs=np.linalg.solve(a,b)
x0,x1=xs
x0

1.857142857142857

In [98]:
x1

2.7142857142857144